trigger:
- master

jobs:
- job: MyJob
  timeoutInMinutes: 120
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
    - task: PowerShell@2
      inputs:
        filePath: 'Test.ps1'

    - task: PowerShell@2
      condition: always()
      inputs:
        filePath: 'CopyFiles.ps1'

    - task: PublishBuildArtifacts@1
      condition: always()
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: logs