trigger:
- master

jobs:
- job: MyJob
  timeoutInMinutes: 120
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
    - task: PowerShell@2
      inputs:
        filePath: 'Test.ps1'

    - task: CopyFiles@2
      condition: always()
      inputs:
        sourceFolder: $env:ChocolateyInstall\log
        contents: '**' 
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: CopyFiles@2
      condition: always()
      inputs:
        sourceFolder: $env:TEMP\chocolatey
        contents: '**' 
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: CopyFiles@2
      condition: always()
      inputs:
        sourceFolder: $env:ChocolateyInstall\config
        contents: '**' 
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      condition: always()
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: logs